# PowerShell Module Manifest for DeployForge
#
# Generated by: DeployForge Team
# Generated on: 2024
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'DeployForge.psm1'

    # Version number of this module.
    ModuleVersion = '0.6.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
    GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

    # Author of this module
    Author = 'DeployForge Team'

    # Company or vendor of this module
    CompanyName = 'DeployForge'

    # Copyright statement for this module
    Copyright = '(c) 2024 DeployForge. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'PowerShell module for Windows deployment image customization. Provides cmdlets for building, analyzing, and customizing Windows installation images with gaming optimizations, debloating, security hardening, and more.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry
    FunctionsToExport = @(
        'Initialize-DeployForge',
        'Build-DeployForgeImage',
        'Set-DeployForgeProfile',
        'Get-DeployForgeProfile',
        'Get-DeployForgeImageInfo',
        'Compare-DeployForgeImage',
        'Test-DeployForgeImage',
        'New-DeployForgePreset',
        'Get-DeployForgePreset',
        'Set-DeployForgePreset',
        'Optimize-DeployForgeGaming',
        'Remove-DeployForgeBloatware'
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry
    AliasesToExport = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{
        PSData = @{
            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @(
                'Windows',
                'Deployment',
                'Image',
                'WIM',
                'Customization',
                'Gaming',
                'Performance',
                'Debloat',
                'Security',
                'DISM'
            )

            # A URL to the license for this module.
            LicenseUri = 'https://github.com/YourOrg/DeployForge/blob/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/YourOrg/DeployForge'

            # A URL to an icon representing this module.
            IconUri = ''

            # ReleaseNotes of this module
            ReleaseNotes = @'
# DeployForge v0.6.0 Release Notes

## New Features
- PowerShell module with native cmdlets
- Interactive CLI tool with profile support
- Preset management system
- Image analysis and comparison tools
- Gaming optimization profiles
- Debloating and privacy tools
- Visual customization engine
- Developer environment builder
- Package manager integration

## Cmdlets
- Build-DeployForgeImage: Build customized images
- Get-DeployForgeImageInfo: Analyze image contents
- Test-DeployForgeImage: Validate image integrity
- Optimize-DeployForgeGaming: Apply gaming optimizations
- Remove-DeployForgeBloatware: Remove unwanted apps
- And more...

## Requirements
- PowerShell 5.1 or later
- Python 3.8 or later
- DeployForge Python package
- Windows 10/11 with DISM

## Installation
Import-Module .\DeployForge.psm1

## Documentation
See README.md for detailed usage examples.
'@

            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            # ExternalModuleDependencies = @()
        }
    }

    # HelpInfo URI of this module
    HelpInfoURI = 'https://github.com/YourOrg/DeployForge/wiki'

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}
