using System;using System.Collections.Generic;using System.Threading;using System.Threading.Tasks;
using Better11.Core.Interfaces;using Better11.Services.BackupRestore;using Moq;using Xunit;
namespace Better11.Tests.BackupRestore;
public class BackupRestoreServiceTests{
private readonly Mock<IPowerShellService> _m;private readonly BackupRestoreService _s;
public BackupRestoreServiceTests(){_m=new Mock<IPowerShellService>();_s=new BackupRestoreService(_m.Object);}
[Fact] public void Ctor()=>Assert.Throws<ArgumentNullException>(()=>new BackupRestoreService(null!));
[Fact] public async Task GetRp(){_m.Setup(p=>p.InvokeListAsync<RestorePointDto>("B11.BackupRestore","Get-B11RestorePoint",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<IReadOnlyList<RestorePointDto>>.Ok(new List<RestorePointDto>()));Assert.True((await _s.GetRestorePointsAsync()).IsSuccess);}
[Fact] public async Task CreateRp(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","New-B11RestorePoint",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.CreateRestorePointAsync("test")).IsSuccess);}
[Fact] public async Task DelRp(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","Remove-B11RestorePoint",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.DeleteRestorePointAsync(1)).IsSuccess);}
[Fact] public async Task GetReg(){_m.Setup(p=>p.InvokeListAsync<RegistryBackupDto>("B11.BackupRestore","Get-B11RegistryBackup",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<IReadOnlyList<RegistryBackupDto>>.Ok(new List<RegistryBackupDto>()));Assert.True((await _s.GetRegistryBackupsAsync()).IsSuccess);}
[Fact] public async Task ExportReg(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","Export-B11RegistryKey",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.ExportRegistryKeyAsync("HKCU","bk")).IsSuccess);}
[Fact] public async Task ImportReg(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","Import-B11RegistryBackup",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.ImportRegistryBackupAsync("f")).IsSuccess);}
[Fact] public async Task GetBkp(){_m.Setup(p=>p.InvokeListAsync<FileBackupDto>("B11.BackupRestore","Get-B11FileBackup",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<IReadOnlyList<FileBackupDto>>.Ok(new List<FileBackupDto>()));Assert.True((await _s.GetFileBackupsAsync()).IsSuccess);}
[Fact] public async Task CreateBkp(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","New-B11FileBackup",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.CreateFileBackupAsync("s","d",true,false)).IsSuccess);}
[Fact] public async Task RestoreBkp(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","Restore-B11FileBackup",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.RestoreFileBackupAsync("b","r")).IsSuccess);}
[Fact] public async Task GetSched(){_m.Setup(p=>p.InvokeListAsync<BackupScheduleDto>("B11.BackupRestore","Get-B11BackupSchedule",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<IReadOnlyList<BackupScheduleDto>>.Ok(new List<BackupScheduleDto>()));Assert.True((await _s.GetSchedulesAsync()).IsSuccess);}
[Fact] public async Task CreateSched(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","New-B11BackupSchedule",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.CreateScheduleAsync("n","s","d","Daily",30)).IsSuccess);}
[Fact] public async Task DelSched(){_m.Setup(p=>p.InvokeAsync<bool>("B11.BackupRestore","Remove-B11BackupSchedule",It.IsAny<Dictionary<string,object>>(),It.IsAny<CancellationToken>())).ReturnsAsync(Result<bool>.Ok(true));Assert.True((await _s.DeleteScheduleAsync("n")).IsSuccess);}
}