#Requires -RunAsAdministrator
<#
APPLY script generated: 2026-02-26 03:24:17Z
Edit $FeatureNames and remove entries you don't want enabled.
#>

[CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact='High')]
param()

$FeatureNames = @(
    'AppServerClient',
    'Client-DeviceLockdown',
    'Client-EmbeddedBootExp',
    'Client-EmbeddedLogon',
    'Client-EmbeddedShellLauncher',
    'Client-KeyboardFilter',
    'Client-ProjFS',
    'Client-UnifiedWriteFilter',
    'Containers',
    'Containers-DisposableClientVM',
    'Containers-HNS',
    'Containers-SDN',
    'Containers-Server-For-Application-Guard',
    'DirectPlay',
    'HostGuardian',
    'HyperV-Guest-KernelInt',
    'HypervisorPlatform',
    'HyperV-KernelInt-VirtualDevice',
    'IIS-ApplicationDevelopment',
    'IIS-ApplicationInit',
    'IIS-ASP',
    'IIS-ASPNET',
    'IIS-ASPNET45',
    'IIS-BasicAuthentication',
    'IIS-CertProvider',
    'IIS-CGI',
    'IIS-ClientCertificateMappingAuthentication',
    'IIS-CommonHttpFeatures',
    'IIS-CustomLogging',
    'IIS-DefaultDocument',
    'IIS-DigestAuthentication',
    'IIS-DirectoryBrowsing',
    'IIS-FTPExtensibility',
    'IIS-FTPServer',
    'IIS-FTPSvc',
    'IIS-HealthAndDiagnostics',
    'IIS-HostableWebCore',
    'IIS-HttpCompressionDynamic',
    'IIS-HttpCompressionStatic',
    'IIS-HttpErrors',
    'IIS-HttpLogging',
    'IIS-HttpRedirect',
    'IIS-HttpTracing',
    'IIS-IIS6ManagementCompatibility',
    'IIS-IISCertificateMappingAuthentication',
    'IIS-IPSecurity',
    'IIS-ISAPIExtensions',
    'IIS-ISAPIFilter',
    'IIS-LegacyScripts',
    'IIS-LoggingLibraries',
    'IIS-ManagementConsole',
    'IIS-ManagementScriptingTools',
    'IIS-ManagementService',
    'IIS-Metabase',
    'IIS-NetFxExtensibility',
    'IIS-NetFxExtensibility45',
    'IIS-ODBCLogging',
    'IIS-Performance',
    'IIS-RequestFiltering',
    'IIS-RequestMonitor',
    'IIS-Security',
    'IIS-ServerSideIncludes',
    'IIS-StaticContent',
    'IIS-URLAuthorization',
    'IIS-WebDAV',
    'IIS-WebServer',
    'IIS-WebServerManagementTools',
    'IIS-WebServerRole',
    'IIS-WebSockets',
    'IIS-WindowsAuthentication',
    'IIS-WMICompatibility',
    'LegacyComponents',
    'MediaPlayback',
    'Microsoft-Hyper-V',
    'Microsoft-Hyper-V-All',
    'Microsoft-Hyper-V-Hypervisor',
    'Microsoft-Hyper-V-Management-Clients',
    'Microsoft-Hyper-V-Management-PowerShell',
    'Microsoft-Hyper-V-Services',
    'Microsoft-Hyper-V-Tools-All',
    'Microsoft-RemoteDesktopConnection',
    'Microsoft-Windows-Subsystem-Linux',
    'MSRDC-Infrastructure',
    'NetFx3',
    'NetFx4-AdvSrvs',
    'NetFx4Extended-ASPNET45',
    'Recall',
    'SearchEngine-Client-Package',
    'ServicesForNFS-ClientOnly',
    'SimpleTCP',
    'SmbDirect',
    'TelnetClient',
    'TFTP',
    'TIFFIFilter',
    'VirtualMachinePlatform',
    'WAS-ConfigurationAPI',
    'WAS-NetFxEnvironment',
    'WAS-ProcessModel',
    'WAS-WindowsActivationService',
    'WCF-HTTP-Activation',
    'WCF-HTTP-Activation45',
    'WCF-MSMQ-Activation45',
    'WCF-NonHTTP-Activation',
    'WCF-Pipe-Activation45',
    'WCF-Services45',
    'WCF-TCP-Activation45',
    'WCF-TCP-PortSharing45',
    'Windows-Defender-Default-Definitions',
    'Windows-Identity-Foundation',
    'WindowsMediaPlayer'
)

foreach ($name in $FeatureNames) {
    if ($PSCmdlet.ShouldProcess("OptionalFeature: $name", "Enable")) {
        try {
            Enable-WindowsOptionalFeature -Online -FeatureName $name -All -NoRestart -ErrorAction Stop | Out-Null
            Write-Host "Enabled: $name" -ForegroundColor Green
        } catch {
            Write-Warning "FAILED enabling $name : $($_.Exception.Message)"
        }
    }
}
Write-Host "Done. Some features may require reboot." -ForegroundColor Yellow

